- name: Run update php command
  ansible.builtin.command: docker-compose run mediawiki php maintenance/update.php --quick
  args:
    chdir: "{{ mediawiki_deploy_dir }}"
  changed_when: true

- name: Run SMW setupStore php command
  ansible.builtin.command: docker-compose run mediawiki php ./extensions/SemanticMediaWiki/maintenance/setupStore.php
  args:
    chdir: "{{ mediawiki_deploy_dir }}"
  changed_when: true
