version: '3'
services:
  mediawiki:
    container_name: wikimipt_mediawiki
    hostname: wikimipt_mediawiki
    image: registry.gitlab.com/fpmi/wikimipt/mediawiki:latest
    restart: always
    ports:
      - 8100:80
    volumes:
      - ./images:/var/www/html/images
      - ./backups:/var/www/html/backups
      - ./logs:/var/log/mediawiki
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - mediawiki-net

  memcached:
    container_name: wikimipt_memcached
    hostname: wikimipt_memcached
    image: memcached:latest
    restart: always
    command: ["-m", "512"]
    networks:
      - mediawiki-net

networks:
  mediawiki-net:
    external: true
