---
- name: Build mediawiki image
  hosts: [localhost]
  tasks:
    - name: Build mediawiki image
      community.docker.docker_image:
        name: registry.gitlab.com/fpmi/wikimipt/mediawiki
        tag: latest
        build:
          path: "{{ project_dir }}/mediawiki-build-1.35"
        source: build
