---
- name: Restart mediawiki database
  hosts: [db]
  roles:
    - percona_mysql
  vars:
    percona_mysql_action: "restart"

- name: Restart mediawiki
  hosts: [mediawiki]
  roles:
    - mediawiki
  vars:
    mediawiki_action: "restart"
