---
- name: Creating necessary files and directories
  ansible.builtin.import_tasks: files_and_folders.yml
  when: percona_mysql_action == "deploy"

- name: Deploy with docker-compose
  ansible.builtin.import_tasks: deploy_docker_compose.yml
  when: percona_mysql_action == "deploy"

- name: Run force restart
  ansible.builtin.import_tasks: force_restart.yml
  when: percona_mysql_action == "restart"
